---
- include: upload_ssh_public_key.yml
# - include: provision_survey.yml
#   vars:
#     droplet_name: chab-survey
#     domains:
#     - collect.simplex2.ninja
#     member_of:
#     - survey
#     - webserver
- include: provision_application.yml
  vars:
    droplet_name: sweplex-staging
    domains:
    - stage.sweplex.com
    member_of:
    - staging
- include: provision_application.yml
  vars:
    droplet_name: sweplex-application
    domains:
    - app.sweplex.com
    member_of:
    - production
