---
- include: upload_ssh_public_key.yml
- include: provision_survey.yml
  vars:
    droplet_name: chab-survey
    domains:
    - collect.simplex2.ninja
    member_of:
    - survey
    - webserver
- include: provision_application.yml
  vars:
    droplet_name: chab-application
    domains:
    - simplex2.ninja
    - www.simplex2.ninja
    member_of:
    - app
    - webserver
    - staging
